units:
  - path: /system/autonomous_available
    type: and
    list:
      - { type: link, link: /system/emergency_stop }
      - { type: link, link: /system/pull_over }
      - { type: link, link: /system/comfortable_stop }

  - path: /system/pull_over_available
    type: and
    list:
      - { type: link, link: /system/emergency_stop }
      - { type: link, link: /system/comfortable_stop }

  - path: /system/comfortable_stop_available
    type: and
    list:
      - { type: link, link: /system/emergency_stop }

  # *******************************************************************************
  # NOTE: Please modify this section according to your environment and requirements.
  # *******************************************************************************
  - path: /system/emergency_stop
    type: and
    list:
      - { type: link, link: /system/001-topic_status-error }
      - { type: link, link: /system/002-emergency_stop_operation-error }

  - path: /system/comfortable_stop
    type: and

  - path: /system/pull_over
    type: and
    list:
      - { type: link, link: /system/005-fms_connection-error }

  - path: /system/none
    type: and
    list:
      - { type: link, link: /system/003-bagpacker_status }
      - { type: link, link: /system/004-bagpacker_disk_space }

  - path: /system/001-topic_status-error
    type: warn-to-ok
    item:
      type: link
      link: /system/001-topic_status

  - path: /system/002-emergency_stop_operation-error
    type: warn-to-ok
    item:
      type: link
      link: /system/002-emergency_stop_operation

  - path: /system/005-fms_connection-error
    type: warn-to-ok
    item:
      type: link
      link: /system/005-fms_connection

  - path: /system/001-topic_status
    type: diag
    node: topic_state_monitor_system_emergency_control_cmd
    name: system_topic_status
    timeout: 1.0

  - path: /system/002-emergency_stop_operation
    type: diag
    node: vehicle_cmd_gate
    name: emergency_stop_operation
    timeout: 1.0

  - path: /system/003-bagpacker_status
    type: diag
    node: ""
    name: rosbag_status
    timeout: 3.0

  - path: /system/004-bagpacker_disk_space
    type: diag
    node: ""
    name: disk_status
    timeout: 3.0

  - path: /system/005-fms_connection
    type: diag
    node: ""
    name: edge_core_internet_connection
    timeout: 10.0
