/**:
  ros__parameters:
    traffic_light:
      stop_margin: 0.5
      tl_state_timeout: 0.36
      stop_time_hysteresis: 0.1
      yellow_lamp_period: 2.75
      enable_pass_judge: true
      enable_rtc: false # If set to true, the scene modules require approval from the rtc (request to cooperate) function. If set to false, the modules can be executed without requiring rtc approval
