/**:
  ros__parameters:
    input_offset_ms: [-10.0, 15.0, 65.00, 40.0, 40.0, 40.0, 40.0, 73.3, 6.7]
    timeout_ms: 70.0
    match_threshold_ms: 50.0
    image_buffer_size: 15
    point_project_to_unrectified_image: false
    debug_mode: false
    filter_scope_min_x: -100.0
    filter_scope_min_y: -100.0
    filter_scope_min_z: -100.0
    filter_scope_max_x: 100.0
    filter_scope_max_y: 100.0
    filter_scope_max_z: 100.0
