/**:
  ros__parameters:
    topic: "/main/planning/scenario_planning/trajectory"
    topic_type: "autoware_planning_msgs/msg/Trajectory" # unnecessary for /tf or /tf_static
    remap_topic: "/planning/topic_relay_controller/trajectory"
    #frame_id: necessary for /tf or /tf_static
    #child_frame_id: necessary for /tf or /tf_static
    qos_depth: 1
    transient_local: false # Change qos to transient_local. Default is volatile.
    best_effort: false # Change qos to best_effort. Default is reliable.
    enable_relay_control: false
    #srv_name: "/system/topic_relay_controller_trajectory/operate" # necessary for enable_relay_control is true
    enable_keep_publishing: true
    update_rate: 10 #necessary for enable_keep_publishing is true
