/**:
  ros__parameters:
    use_operation_mode_availability: false
    rate: 10.0
    input_qos_depth: 1000
    graph_qos_depth: 1

    use_command_mode_mappings: true
    command_mode_mappings:
      - "{mode: sub_ecu_in_lane_stop_0_3g,  path: /autoware/modes/sub_ecu_in_lane_stop_0_3g}"
