/**:
  ros__parameters:
    devices: ["enp5s0f0"]
    monitor_program: "greengrass"
    enable_traffic_monitor: false
    crc_error_check_duration: 1
    crc_error_count_threshold: 1
    reassembles_failed_check_duration: 1
    reassembles_failed_check_count: 1
    udp_buf_errors_check_duration: 1
    udp_buf_errors_check_count: 1
