/**:
  ros__parameters:
    system:
      type: diagnostic_aggregator/AnalyzerGroup
      path: system
      analyzers:
        debug_data_logger:
          type: diagnostic_aggregator/AnalyzerGroup
          path: debug_data_logger
          analyzers:
            storage_error:
              type: diagnostic_aggregator/GenericAnalyzer
              path: storage_error
              contains: ["bagpacker"]
              timeout: 3.0
        fms_connection:
          type: diagnostic_aggregator/AnalyzerGroup
          path: fms_connection
          analyzers:
            connection_error:
              type: diagnostic_aggregator/GenericAnalyzer
              path: connection_error
              contains: ["edge_core_internet_connection"]
              timeout: 10.0
