/**:
  ros__parameters:
    max_vel: 9.72           # max velocity limit [m/s]

    # constraints param for normal driving
    normal:
      min_acc: -1.0         # min deceleration [m/ss]
      max_acc: 1.0          # max acceleration [m/ss]
      min_jerk: -0.6        # min jerk [m/sss]
      max_jerk: 0.6         # max jerk [m/sss]

    # constraints to be observed
    limit:
      min_acc: -6.0         # min deceleration limit [m/ss]
      max_acc: 1.0          # max acceleration limit [m/ss]
      min_jerk: -20.0       # min jerk limit [m/sss]
      max_jerk: 20.0        # max jerk limit [m/sss]
